SageValley_Ice_MapScripts::
	.byte 0

SageValley_Ice_EventScript_GymSign::
	msgbox SageValley_Ice_Text_GymSign, MSGBOX_SIGN
	end

SageValley_Ice_Text_GymSign:
	.string "SAGE VILLAGE TRAINER'S GAUNTLET\p"
	.string "“The Highest Stage of training.”$"

SageValley_Ice_EventScript_Poochyena::
	msgbox SageValley_Ice_Text_Poochyena, MSGBOX_NPC
	end

SageValley_Ice_Text_Poochyena:
	.string "BOW BOW!$"

SageValley_Ice_EventScript_Azumarill::
	msgbox SageValley_Ice_Text_Azumarill, MSGBOX_NPC
	end

SageValley_Ice_Text_Azumarill:
	.string "Azu?$"

SageValley_Ice_EventScript_Man1::
	msgbox SageValley_Ice_Text_Man1, MSGBOX_NPC
	end

SageValley_Ice_Text_Man1:
	.string "The Sage Island.\p"
	.string "This island is located outside of Hoenn.\p"
	.string "The harsh mountains of this island,\p"
	.string "stops cold wind from the Ocean from\p"
	.string "entering Hoenn.\p"
	.string "Hence why Hoenn's weather is tropical.$"

SageValley_Ice_EventScript_Man2::
	msgbox SageValley_Ice_Text_Man2, MSGBOX_NPC
	end

SageValley_Ice_Text_Man2:
	.string "The Glacial Path was supposed to\n"
	.string "be a long winding path.\p"
	.string "But works stopped due to the harsh cold\p"
	.string "past the area.$"

SageValley_Ice_EventScript_Woman::
	msgbox SageValley_Ice_Text_Woman, MSGBOX_NPC
	end

SageValley_Ice_Text_Woman:
	.string "Maxie is my uncle.\p"
	.string "Yes, this is our home.\p"
	.string "He went off to visit Archie in Silver Island.\p"
	.string "I love how they went from enemies to friends.$"

SageValley_Ice_EventScript_VillSign::
	msgbox SageValley_Ice_Text_VillSign, MSGBOX_SIGN
	end

SageValley_Ice_Text_VillSign:
	.string "SAGE VILLAGE\p"
	.string "“The lone village thriving in the harsh cold.”"
