BattleFrontier_Lounge7_MapScripts::
	.byte 0

@special ChooseMonForMoveTutor
BattleFrontier_Lounge7_EventScript_LeftMoveTutor::
	lock
	faceplayer
	setvar VAR_TEMP_C, SCROLL_MULTI_BF_MOVE_TUTOR_1
	goto_if_set FLAG_MET_FRONTIER_BEAUTY_MOVE_TUTOR, BattleFrontier_Lounge7_EventScript_AlreadyMetLeftTutor
	msgbox BattleFrontier_Lounge7_Text_LeftTutorIntro, MSGBOX_DEFAULT
	setflag FLAG_MET_FRONTIER_BEAUTY_MOVE_TUTOR
	goto BattleFrontier_Lounge7_EventScript_ChooseLeftTutorMove
	end

BattleFrontier_Lounge7_EventScript_AlreadyMetLeftTutor::
	msgbox BattleFrontier_Lounge7_Text_LeftTutorWelcomeBack, MSGBOX_DEFAULT
	goto BattleFrontier_Lounge7_EventScript_ChooseLeftTutorMove
	end

BattleFrontier_Lounge7_EventScript_ChooseLeftTutorMove::
	message BattleFrontier_Lounge7_Text_TeachWhichMove
	waitmessage
	special ShowBattlePointsWindow
	setvar VAR_TEMP_FRONTIER_TUTOR_ID, 0
	setvar VAR_0x8004, SCROLL_MULTI_BF_MOVE_TUTOR_1
	setvar VAR_0x8006, 0
	special ShowScrollableMultichoice
	copyvar VAR_TEMP_FRONTIER_TUTOR_SELECTION, VAR_RESULT
	switch VAR_RESULT
	case 0, BattleFrontier_Lounge7_EventScript_Softboiled
	case 1, BattleFrontier_Lounge7_EventScript_DualWingbeat
	case 2, BattleFrontier_Lounge7_EventScript_SeismicToss
	case 3, BattleFrontier_Lounge7_EventScript_DreamEater
	case 4, BattleFrontier_Lounge7_EventScript_MegaPunch
	case 5, BattleFrontier_Lounge7_EventScript_BlastBurn
	case 6, BattleFrontier_Lounge7_EventScript_HydroCannon
	case 7, BattleFrontier_Lounge7_EventScript_FrenzyPlant
	case 8, BattleFrontier_Lounge7_EventScript_GunkShot
	case 9, BattleFrontier_Lounge7_EventScript_SeedBomb
	case 10, BattleFrontier_Lounge7_EventScript_DrillRun
	case 11, BattleFrontier_Lounge7_EventScript_Bounce
	case 12, BattleFrontier_Lounge7_EventScript_MegaKick
	case 13, BattleFrontier_Lounge7_EventScript_BodySlam
	case 14, BattleFrontier_Lounge7_EventScript_RockSlide
	case 15, BattleFrontier_Lounge7_EventScript_Counter
	case 16, BattleFrontier_Lounge7_EventScript_ThunderWave
	case 17, BattleFrontier_Lounge7_EventScript_DragonDance
	case 18, BattleFrontier_Lounge7_EventScript_DracoMeteor
	case 19, BattleFrontier_Lounge7_EventScript_StealthRock
	case 20, BattleFrontier_Lounge7_EventScript_Defog
	case 21, BattleFrontier_Lounge7_EventScript_Outrage
	case 22, BattleFrontier_Lounge7_EventScript_DualChop
	case 23, BattleFrontier_Lounge7_EventScript_LowKick
	case 24, BattleFrontier_Lounge7_EventScript_VoltTackle
	case 25, BattleFrontier_Lounge7_EventScript_ExitTutorMoveSelect
	case MULTI_B_PRESSED, BattleFrontier_Lounge7_EventScript_ExitTutorMoveSelect
	end

BattleFrontier_Lounge7_EventScript_ChooseNewLeftTutorMove::
	message BattleFrontier_Lounge7_Text_TeachWhichMove
	waitmessage
	setvar VAR_TEMP_FRONTIER_TUTOR_ID, 0
	setvar VAR_0x8004, SCROLL_MULTI_BF_MOVE_TUTOR_1
	setvar VAR_0x8006, 1
	special ShowScrollableMultichoice
	copyvar VAR_TEMP_FRONTIER_TUTOR_SELECTION, VAR_RESULT
	switch VAR_RESULT
	case 0, BattleFrontier_Lounge7_EventScript_Softboiled
	case 1, BattleFrontier_Lounge7_EventScript_DualWingbeat
	case 2, BattleFrontier_Lounge7_EventScript_SeismicToss
	case 3, BattleFrontier_Lounge7_EventScript_DreamEater
	case 4, BattleFrontier_Lounge7_EventScript_MegaPunch
	case 5, BattleFrontier_Lounge7_EventScript_BlastBurn
	case 6, BattleFrontier_Lounge7_EventScript_HydroCannon
	case 7, BattleFrontier_Lounge7_EventScript_FrenzyPlant
	case 8, BattleFrontier_Lounge7_EventScript_GunkShot
	case 9, BattleFrontier_Lounge7_EventScript_SeedBomb
	case 10, BattleFrontier_Lounge7_EventScript_DrillRun
	case 11, BattleFrontier_Lounge7_EventScript_Bounce
	case 12, BattleFrontier_Lounge7_EventScript_MegaKick
	case 13, BattleFrontier_Lounge7_EventScript_BodySlam
	case 14, BattleFrontier_Lounge7_EventScript_RockSlide
	case 15, BattleFrontier_Lounge7_EventScript_Counter
	case 16, BattleFrontier_Lounge7_EventScript_ThunderWave
	case 17, BattleFrontier_Lounge7_EventScript_DragonDance
	case 18, BattleFrontier_Lounge7_EventScript_DracoMeteor
	case 19, BattleFrontier_Lounge7_EventScript_StealthRock
	case 20, BattleFrontier_Lounge7_EventScript_Defog
	case 21, BattleFrontier_Lounge7_EventScript_Outrage
	case 22, BattleFrontier_Lounge7_EventScript_DualChop
	case 23, BattleFrontier_Lounge7_EventScript_LowKick
	case 24, BattleFrontier_Lounge7_EventScript_VoltTackle
	case 25, BattleFrontier_Lounge7_EventScript_ExitTutorMoveSelect
	case MULTI_B_PRESSED, BattleFrontier_Lounge7_EventScript_ExitTutorMoveSelect
	end

BattleFrontier_Lounge7_EventScript_Softboiled::
	setvar VAR_0x8008, 16
	setvar VAR_0x8005, MOVE_SOFT_BOILED
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_DualWingbeat::
	setvar VAR_0x8008, 16
	setvar VAR_0x8005, MOVE_DUAL_WINGBEAT
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_SeismicToss::
	setvar VAR_0x8008, 24
	setvar VAR_0x8005, MOVE_SEISMIC_TOSS
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_DreamEater::
	setvar VAR_0x8008, 24
	setvar VAR_0x8005, MOVE_DREAM_EATER
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_MegaPunch::
	setvar VAR_0x8008, 24
	setvar VAR_0x8005, MOVE_MEGA_PUNCH
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_BlastBurn::
	setvar VAR_0x8008, 24
	setvar VAR_0x8005, MOVE_BLAST_BURN
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_HydroCannon::
	setvar VAR_0x8008, 24
	setvar VAR_0x8005, MOVE_HYDRO_CANNON
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_FrenzyPlant::
	setvar VAR_0x8008, 24
	setvar VAR_0x8005, MOVE_FRENZY_PLANT
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_GunkShot::
	setvar VAR_0x8008, 24
	setvar VAR_0x8005, MOVE_GUNK_SHOT
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_SeedBomb::
	setvar VAR_0x8008, 24
	setvar VAR_0x8005, MOVE_SEED_BOMB
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_DrillRun::
	setvar VAR_0x8008, 24
	setvar VAR_0x8005, MOVE_DRILL_RUN
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_Bounce::
	setvar VAR_0x8008, 24
	setvar VAR_0x8005, MOVE_BOUNCE
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_MegaKick::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_MEGA_KICK
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_BodySlam::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_BODY_SLAM
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_RockSlide::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_ROCK_SLIDE
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_Counter::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_COUNTER
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_ThunderWave::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_THUNDER_WAVE
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_DragonDance::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_DRAGON_DANCE
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_DracoMeteor::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_DRACO_METEOR
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_StealthRock::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_STEALTH_ROCK
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_Defog::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_DEFOG
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_Outrage::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_OUTRAGE
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_DualChop::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_DUAL_CHOP
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_LowKick::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_LOW_KICK
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_RightMoveTutor::
	lock
	faceplayer
	setvar VAR_TEMP_C, SCROLL_MULTI_BF_MOVE_TUTOR_2
	goto_if_set FLAG_MET_FRONTIER_SWIMMER_MOVE_TUTOR, BattleFrontier_Lounge7_EventScript_AlreadyMetRightTutor
	msgbox BattleFrontier_Lounge7_Text_RightTutorIntro, MSGBOX_DEFAULT
	setflag FLAG_MET_FRONTIER_SWIMMER_MOVE_TUTOR
	goto BattleFrontier_Lounge7_EventScript_ChooseRightTutorMove
	end

BattleFrontier_Lounge7_EventScript_AlreadyMetRightTutor::
	msgbox BattleFrontier_Lounge7_Text_RightTutorWelcomeBack, MSGBOX_DEFAULT
	goto BattleFrontier_Lounge7_EventScript_ChooseRightTutorMove
	end

BattleFrontier_Lounge7_EventScript_ChooseRightTutorMove::
	message BattleFrontier_Lounge7_Text_TeachWhichMove
	waitmessage
	special ShowBattlePointsWindow
	setvar VAR_TEMP_FRONTIER_TUTOR_ID, 1
	setvar VAR_0x8004, SCROLL_MULTI_BF_MOVE_TUTOR_2
	setvar VAR_0x8006, 0
	special ShowScrollableMultichoice
	copyvar VAR_TEMP_FRONTIER_TUTOR_SELECTION, VAR_RESULT
	switch VAR_RESULT
	case 0, BattleFrontier_Lounge7_EventScript_DefenseCurl
	case 1, BattleFrontier_Lounge7_EventScript_BugBite
	case 2, BattleFrontier_Lounge7_EventScript_Snore
	case 3, BattleFrontier_Lounge7_EventScript_MudSlap
	case 4, BattleFrontier_Lounge7_EventScript_Swift
	case 5, BattleFrontier_Lounge7_EventScript_IcyWind
	case 6, BattleFrontier_Lounge7_EventScript_GrassPledge
	case 7, BattleFrontier_Lounge7_EventScript_WaterPledge
	case 8, BattleFrontier_Lounge7_EventScript_FirePledge
	case 9, BattleFrontier_Lounge7_EventScript_ScaleShot
	case 10, BattleFrontier_Lounge7_EventScript_LashOut
	case 11, BattleFrontier_Lounge7_EventScript_Coaching
	case 12, BattleFrontier_Lounge7_EventScript_Endure
	case 13, BattleFrontier_Lounge7_EventScript_PsychUp
	case 14, BattleFrontier_Lounge7_EventScript_IcePunch
	case 15, BattleFrontier_Lounge7_EventScript_ThunderPunch
	case 16, BattleFrontier_Lounge7_EventScript_FirePunch
	case 17, BattleFrontier_Lounge7_EventScript_Roost
	case 18, BattleFrontier_Lounge7_EventScript_Tailwind
	case 19, BattleFrontier_Lounge7_EventScript_Superpower
	case 20, BattleFrontier_Lounge7_EventScript_KnockOff
	case 21, BattleFrontier_Lounge7_EventScript_IronHead
	case 22, BattleFrontier_Lounge7_EventScript_ZenHeadbutt
	case 23, BattleFrontier_Lounge7_EventScript_DragonAscent
	case 24, BattleFrontier_Lounge7_EventScript_VoltTackle
	case 25, BattleFrontier_Lounge7_EventScript_ExitTutorMoveSelect
	case MULTI_B_PRESSED, BattleFrontier_Lounge7_EventScript_ExitTutorMoveSelect
	end

BattleFrontier_Lounge7_EventScript_ChooseNewRightTutorMove::
	message BattleFrontier_Lounge7_Text_TeachWhichMove
	waitmessage
	setvar VAR_TEMP_FRONTIER_TUTOR_ID, 1
	setvar VAR_0x8004, SCROLL_MULTI_BF_MOVE_TUTOR_2
	setvar VAR_0x8006, 1
	special ShowScrollableMultichoice
	copyvar VAR_TEMP_FRONTIER_TUTOR_SELECTION, VAR_RESULT
	switch VAR_RESULT
	case 0, BattleFrontier_Lounge7_EventScript_DefenseCurl
	case 1, BattleFrontier_Lounge7_EventScript_BugBite
	case 2, BattleFrontier_Lounge7_EventScript_Snore
	case 3, BattleFrontier_Lounge7_EventScript_MudSlap
	case 4, BattleFrontier_Lounge7_EventScript_Swift
	case 5, BattleFrontier_Lounge7_EventScript_IcyWind
	case 6, BattleFrontier_Lounge7_EventScript_GrassPledge
	case 7, BattleFrontier_Lounge7_EventScript_WaterPledge
	case 8, BattleFrontier_Lounge7_EventScript_FirePledge
	case 9, BattleFrontier_Lounge7_EventScript_ScaleShot
	case 10, BattleFrontier_Lounge7_EventScript_LashOut
	case 11, BattleFrontier_Lounge7_EventScript_Coaching
	case 12, BattleFrontier_Lounge7_EventScript_Endure
	case 13, BattleFrontier_Lounge7_EventScript_PsychUp
	case 14, BattleFrontier_Lounge7_EventScript_IcePunch
	case 15, BattleFrontier_Lounge7_EventScript_ThunderPunch
	case 16, BattleFrontier_Lounge7_EventScript_FirePunch
	case 17, BattleFrontier_Lounge7_EventScript_Roost
	case 18, BattleFrontier_Lounge7_EventScript_Tailwind
	case 19, BattleFrontier_Lounge7_EventScript_Superpower
	case 20, BattleFrontier_Lounge7_EventScript_KnockOff
	case 21, BattleFrontier_Lounge7_EventScript_IronHead
	case 22, BattleFrontier_Lounge7_EventScript_ZenHeadbutt
	case 23, BattleFrontier_Lounge7_EventScript_DragonAscent
	case 24, BattleFrontier_Lounge7_EventScript_VoltTackle
	case 25, BattleFrontier_Lounge7_EventScript_ExitTutorMoveSelect
	case MULTI_B_PRESSED, BattleFrontier_Lounge7_EventScript_ExitTutorMoveSelect
	end

BattleFrontier_Lounge7_EventScript_DefenseCurl::
	setvar VAR_0x8008, 16
	setvar VAR_0x8005, MOVE_DEFENSE_CURL
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_BugBite::
	setvar VAR_0x8008, 16
	setvar VAR_0x8005, MOVE_BUG_BITE
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_Snore::
	setvar VAR_0x8008, 24
	setvar VAR_0x8005, MOVE_SNORE
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_MudSlap::
	setvar VAR_0x8008, 24
	setvar VAR_0x8005, MOVE_MUD_SLAP
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_Swift::
	setvar VAR_0x8008, 24
	setvar VAR_0x8005, MOVE_SWIFT
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_IcyWind::
	setvar VAR_0x8008, 24
	setvar VAR_0x8005, MOVE_ICY_WIND
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_GrassPledge::
	setvar VAR_0x8008, 24
	setvar VAR_0x8005, MOVE_GRASS_PLEDGE
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_WaterPledge::
	setvar VAR_0x8008, 24
	setvar VAR_0x8005, MOVE_WATER_PLEDGE
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_FirePledge::
	setvar VAR_0x8008, 24
	setvar VAR_0x8005, MOVE_FIRE_PLEDGE
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_ScaleShot::
	setvar VAR_0x8008, 24
	setvar VAR_0x8005, MOVE_SCALE_SHOT
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_LashOut::
	setvar VAR_0x8008, 24
	setvar VAR_0x8005, MOVE_LASH_OUT
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_Coaching::
	setvar VAR_0x8008, 24
	setvar VAR_0x8005, MOVE_COACHING
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_Endure::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_ENDURE
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_PsychUp::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_PSYCH_UP
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_IcePunch::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_ICE_PUNCH
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_ThunderPunch::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_THUNDER_PUNCH
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_FirePunch::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_FIRE_PUNCH
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_Roost::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_ROOST
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_Tailwind::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_TAILWIND
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_Superpower::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_SUPERPOWER
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_KnockOff::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_KNOCK_OFF
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_IronHead::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_IRON_HEAD
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_ZenHeadbutt::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_ZEN_HEADBUTT
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_DragonAscent::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_DRAGON_ASCENT
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_VoltTackle::
	setvar VAR_0x8008, 48
	setvar VAR_0x8005, MOVE_VOLT_TACKLE
	goto BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection
	end

BattleFrontier_Lounge7_EventScript_ExitTutorMoveSelect::
	special CloseBattleFrontierTutorWindow
	special CloseBattlePointsWindow
	msgbox BattleFrontier_Lounge7_Text_YouDontWantTo, MSGBOX_DEFAULT
	release
	end

BattleFrontier_Lounge7_EventScript_CancelChooseMon::
	msgbox BattleFrontier_Lounge7_Text_YouDontWantTo, MSGBOX_DEFAULT
	release
	end

@ VAR_0x8008 is the price
@ VAR_TEMP_C is the scroll multichoice ID
@ VAR_TEMP_FRONTIER_TUTOR_SELECTION is the move selection
@ VAR_TEMP_FRONTIER_TUTOR_ID is which move tutor was spoken to
BattleFrontier_Lounge7_EventScript_ConfirmMoveSelection::
	special BufferBattleFrontierTutorMoveName
	buffernumberstring STR_VAR_2, VAR_0x8008
	msgbox BattleFrontier_Lounge7_Text_MoveWillBeXBattlePoints, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, BattleFrontier_Lounge7_EventScript_ChooseNewMove
	specialvar VAR_TEMP_1, GetFrontierBattlePoints
	goto_if_ge VAR_TEMP_1, VAR_0x8008, BattleFrontier_Lounge7_EventScript_TeachTutorMove
	msgbox BattleFrontier_Lounge7_Text_HaventGotEnoughPoints, MSGBOX_DEFAULT
	goto BattleFrontier_Lounge7_EventScript_ChooseNewMove
	end


BattleFrontier_Lounge7_EventScript_TeachTutorMove::
	msgbox BattleFrontier_Lounge7_Text_TeachMoveToWhichMon, MSGBOX_DEFAULT
	fadescreen FADE_TO_BLACK
	special CloseBattlePointsWindow
	special CloseBattleFrontierTutorWindow
	chooseboxmon SELECT_PC_MON_MOVE_TUTOR
	waitstate
	goto_if_eq VAR_RESULT, FALSE, BattleFrontier_Lounge7_EventScript_CancelChooseMon
	msgbox BattleFrontier_Lounge7_Text_IllTakeBattlePoints, MSGBOX_DEFAULT
	copyvar VAR_0x8004, VAR_0x8008
	special TakeFrontierBattlePoints
	release
	end

BattleFrontier_Lounge7_EventScript_ChooseNewMove::
	goto_if_eq VAR_TEMP_FRONTIER_TUTOR_ID, 0, BattleFrontier_Lounge7_EventScript_ChooseNewLeftTutorMove
	goto BattleFrontier_Lounge7_EventScript_ChooseNewRightTutorMove
	end

BattleFrontier_Lounge7_EventScript_Sailor::
	msgbox BattleFrontier_Lounge7_Text_ThinkLadiesDontGetAlong, MSGBOX_NPC
	end

BattleFrontier_Lounge7_EventScript_Gentleman::
	msgbox BattleFrontier_Lounge7_Text_LadiesWereStrongAndBeautiful, MSGBOX_NPC
	end

BattleFrontier_Lounge7_Text_LeftTutorIntro:
	.string "Buhahaha!\p"
	.string "You couldn't tell it from looking now,\n"
	.string "but I used to be one tough TRAINER.\p"
	.string "I had a reputation as the toughest\n"
	.string "BEAUTY around, I tell you!\p"
	.string "… … … … … …\p"
	.string "What is it now?\n"
	.string "You don't believe me.\p"
	.string "I'm not like that blowhard woman over\n"
	.string "there. I'm actually talented!\p"
	.string "Let me prove it to you.\n"
	.string "I can teach your POKéMON special and\l"
	.string "yet cute moves.\p"
	.string "But my lessons don't come free.\n"
	.string "How about paying for the moves I teach\l"
	.string "with a wee bit of Battle Points?$"

BattleFrontier_Lounge7_Text_LeftTutorWelcomeBack:
	.string "Buhahaha!\p"
	.string "Are you back to learn special and\n"
	.string "yet cute POKéMON moves?$"

BattleFrontier_Lounge7_Text_TeachWhichMove:
	.string "Fine, fine, look here!\n"
	.string "Which move should I teach?$"

BattleFrontier_Lounge7_Text_MoveWillBeXBattlePoints:
	.string "The move {STR_VAR_1}, is it?\n"
	.string "That will be {STR_VAR_2} Battle Points, okay?$"

BattleFrontier_Lounge7_Text_TeachMoveToWhichMon:
	.string "Fine, fine, now pick the POKéMON\n"
	.string "I should teach the move to.$"

BattleFrontier_Lounge7_Text_HaventGotEnoughPoints:
	.string "What the…\n"
	.string "You haven't got enough Battle Points!$"

BattleFrontier_Lounge7_Text_IllTakeBattlePoints:
	.string "Do you see how skilled I am now?\n"
	.string "I'll take your Battle Points, thanks!$"

BattleFrontier_Lounge7_Text_YouDontWantTo:
	.string "What's that?\n"
	.string "You don't want to…\p"
	.string "If you want to see how skilled I am,\n"
	.string "you come see me anytime!$"

BattleFrontier_Lounge7_Text_RightTutorIntro:
	.string "Ihihihi!\p"
	.string "I know it's hard to see now, but I used\n"
	.string "to be one fantastic TRAINER.\p"
	.string "I had a reputation as the most\n"
	.string "invincible SWIMMER around, I tell you!\p"
	.string "… … … … … …\p"
	.string "What's wrong?\n"
	.string "You don't believe me.\p"
	.string "I'm not like that buffoonish woman over\n"
	.string "there. I'm actually experienced!\p"
	.string "I can prove it to you.\n"
	.string "I can teach your POKéMON hard and\l"
	.string "yet pretty moves.\p"
	.string "But my lessons don't come free.\n"
	.string "How about paying for the moves I teach\l"
	.string "with a wee bit of Battle Points?$"

BattleFrontier_Lounge7_Text_RightTutorWelcomeBack:
	.string "Ihihihi!\p"
	.string "Have you come to learn hard and\n"
	.string "yet pretty POKéMON moves?$"

BattleFrontier_Lounge7_Text_ThinkLadiesDontGetAlong:
	.string "Those ladies, the way they bad-mouth\n"
	.string "each other, you probably think that\l"
	.string "they don't get along.\p"
	.string "But if that were true, they wouldn't\n"
	.string "stay out here together, would they?$"

BattleFrontier_Lounge7_Text_LadiesWereStrongAndBeautiful:
	.string "When I was just a wee YOUNGSTER,\n"
	.string "those ladies were strong and beautiful.\p"
	.string "They were idols among us TRAINERS.\p"
	.string "Even now, age hasn't dulled their\n"
	.string "abilities.\p"
	.string "In fact, their POKéMON moves have\n"
	.string "grown even more polished.\p"
	.string "But… For some reason, I can't help\n"
	.string "but feel this…\p"
	.string "Time is so cruel…$"

BattleFrontier_Lounge7_Text_DualWingbeatDesc::
	.string "Strikes the foe\n"
	.string "twice with wings\n"
	.string "in succession.$"

BattleFrontier_Lounge7_Text_BlastBurnDesc::
	.string "Powerful fire\n"
	.string "attack; the user\n"
	.string "must rest later.$"

BattleFrontier_Lounge7_Text_HydroCannonDesc::
	.string "Powerful water\n"
	.string "attack; the user\n"
	.string "must rest later.$"

BattleFrontier_Lounge7_Text_FrenzyPlantDesc::
	.string "Powerful grass\n"
	.string "attack; the user\n"
	.string "must rest later.$"

BattleFrontier_Lounge7_Text_GunkShotDesc::
	.string "Shoots filth at\n"
	.string "the foe, which\n"
	.string "may poison it.$"

BattleFrontier_Lounge7_Text_SeedBombDesc::
	.string "Bombards the foe\n"
	.string "with a barrage\n"
	.string "of hard seeds.$"

BattleFrontier_Lounge7_Text_DrillRunDesc::
	.string "A spinning drill\n"
	.string "attack that hits\n"
	.string "critically.$"

BattleFrontier_Lounge7_Text_BounceDesc::
	.string "Bounces up and\n"
	.string "hits the foe\n"
	.string "on turn two.$"

BattleFrontier_Lounge7_Text_DracoMeteorDesc::
	.string "Comets rain down\n"
	.string "sharply lowering\n"
	.string "Sp. Atk stat.$"

BattleFrontier_Lounge7_Text_StealthRockDesc::
	.string "Lays a trap of\n"
	.string "floating stones\n"
	.string "on the foe.$"

BattleFrontier_Lounge7_Text_DefogDesc::
	.string "Clears fog and\n"
	.string "removes barriers\n"
	.string "from the foe.$"

BattleFrontier_Lounge7_Text_OutrageDesc::
	.string "A thrashing move\n"
	.string "that confuses the\n"
	.string "user afterward.$"

BattleFrontier_Lounge7_Text_DualChopDesc::
	.string "Strikes the foe\n"
	.string "twice with hard\n"
	.string "chopping blows.$"

BattleFrontier_Lounge7_Text_LowKickDesc::
	.string "A kick that may\n"
	.string "make the foe\n"
	.string "flinch.$"

BattleFrontier_Lounge7_Text_VoltTackleDesc::
	.string "A life-risking\n"
	.string "tackle that also\n"
	.string "hurts the user.$"

BattleFrontier_Lounge7_Text_BugBiteDesc::
	.string "Bites the foe to\n"
	.string "steal the effect\n"
	.string "of its berry.$"

BattleFrontier_Lounge7_Text_GrassPledgeDesc::
	.string "A grassy attack\n"
	.string "that gains power\n"
	.string "with others.$"

BattleFrontier_Lounge7_Text_WaterPledgeDesc::
	.string "A watery attack\n"
	.string "that gains power\n"
	.string "with others.$"

BattleFrontier_Lounge7_Text_FirePledgeDesc::
	.string "A fiery attack\n"
	.string "that gains power\n"
	.string "with others.$"

BattleFrontier_Lounge7_Text_ScaleShotDesc::
	.string "Fires scales to\n"
	.string "hit 2-5 times,\n"
	.string "lowers Defense.$"

BattleFrontier_Lounge7_Text_LashOutDesc::
	.string "Attacks if stats\n"
	.string "were lowered\n"
	.string "this turn.$"

BattleFrontier_Lounge7_Text_CoachingDesc::
	.string "Coaches the ally\n"
	.string "to boost its\n"
	.string "Attack and Def.$"

BattleFrontier_Lounge7_Text_RoostDesc::
	.string "Restores up to\n"
	.string "half the user's\n"
	.string "maximum HP.$"

BattleFrontier_Lounge7_Text_TailwindDesc::
	.string "A gust that boosts\n"
	.string "the team's Speed\n"
	.string "for four turns.$"

BattleFrontier_Lounge7_Text_SuperpowerDesc::
	.string "Strong attack\n"
	.string "that lowers the\n"
	.string "user's stats.$"

BattleFrontier_Lounge7_Text_KnockOffDesc::
	.string "Knocks away the\n"
	.string "foe's held item\n"
	.string "to make it unusable.$"

BattleFrontier_Lounge7_Text_IronHeadDesc::
	.string "A slam with iron\n"
	.string "that may make\n"
	.string "the foe flinch.$"

BattleFrontier_Lounge7_Text_ZenHeadbuttDesc::
	.string "A headbutt with\n"
	.string "mental power;\n"
	.string "may cause flinch.$"

BattleFrontier_Lounge7_Text_DragonAscentDesc::
	.string "A dive from the\n"
	.string "sky; lowers the\n"
	.string "user's Def/SpDef.$"

BattleFrontier_Lounge7_Text_SoftboiledDesc::
	.string "Recovers up to\n"
	.string "half the user's\n"
	.string "maximum HP.$"

BattleFrontier_Lounge7_Text_SeismicTossDesc::
	.string "Inflicts damage\n"
	.string "identical to the\n"
	.string "user's level.$"

BattleFrontier_Lounge7_Text_DreamEaterDesc::
	.string "Recovers half the\n"
	.string "damage inflicted\n"
	.string "on a sleeping foe.$"

BattleFrontier_Lounge7_Text_MegaPunchDesc::
	.string "A strong punch\n"
	.string "thrown with\n"
	.string "incredible power.$"

BattleFrontier_Lounge7_Text_MegaKickDesc::
	.string "An extremely\n"
	.string "powerful kick with\n"
	.string "intense force.$"

BattleFrontier_Lounge7_Text_BodySlamDesc::
	.string "A full-body slam\n"
	.string "that may cause\n"
	.string "paralysis.$"

BattleFrontier_Lounge7_Text_RockSlideDesc::
	.string "Large boulders\n"
	.string "are hurled. May\n"
	.string "cause flinching.$"

BattleFrontier_Lounge7_Text_CounterDesc::
	.string "Retaliates any\n"
	.string "physical hit with\n"
	.string "double the power.$"

BattleFrontier_Lounge7_Text_ThunderWaveDesc::
	.string "A weak jolt of\n"
	.string "electricity that\n"
	.string "paralyzes the foe.$"

BattleFrontier_Lounge7_Text_DragonDanceDesc::
	.string "A special dance\n"
	.string "that raises\n"
	.string "SPEED & ATTACK.$"

BattleFrontier_Lounge7_Text_DefenseCurlDesc::
	.string "Curls up to con-\n"
	.string "ceal weak spots\n"
	.string "and raise DEFENSE.$"

BattleFrontier_Lounge7_Text_SnoreDesc::
	.string "A loud attack\n"
	.string "that can be used\n"
	.string "only while asleep.$"

BattleFrontier_Lounge7_Text_MudSlapDesc::
	.string "Hurls mud in the\n"
	.string "foe's face to re-\n"
	.string "duce its accuracy.$"

BattleFrontier_Lounge7_Text_SwiftDesc::
	.string "Sprays star-\n"
	.string "shaped rays\n"
	.string "that never miss.$"

BattleFrontier_Lounge7_Text_IcyWindDesc::
	.string "A chilling attack\n"
	.string "that lowers the\n"
	.string "foe's SPEED.$"

BattleFrontier_Lounge7_Text_EndureDesc::
	.string "Endures any at-\n"
	.string "tack for 1 turn,\n"
	.string "leaving 1HP.$"

BattleFrontier_Lounge7_Text_PsychUpDesc::
	.string "Copies the foe's\n"
	.string "effect(s) and\n"
	.string "gives to the user.$"

BattleFrontier_Lounge7_Text_IcePunchDesc::
	.string "An icy punch\n"
	.string "that may\n"
	.string "freeze the foe.$"

BattleFrontier_Lounge7_Text_ThunderPunchDesc::
	.string "An electrified\n"
	.string "punch that may\n"
	.string "paralyze the foe.$"

BattleFrontier_Lounge7_Text_FirePunchDesc::
	.string "A fiery punch\n"
	.string "that may burn\n"
	.string "the foe.$"

